server:
  port: ${PORT}

spring:
  datasource:
    url: jdbc:postgresql://localhost:${PORTS}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_SMTP}
    password: ${PASSWORD_SMTP}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expiration: ${JWT_EXPIRATION}
  key: ${JWT_KEY}
