server:
  port: ${PORT}

spring:
  datasource:
    url: jdbc:postgresql://localhost:${PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  expiration: ${JWT_EXPIRATION}
  key: ${JWT_KEY}
