server:
  port: ${PORT}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${USER_SMTP}
    password: ${PASSWORD_SMTP}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expiration: ${JWT_EXPIRATION}
  key: ${JWT_KEY}
